server:
  port: 8083
  servlet:
    context-path: /api

spring:
  application:
    name: iptv-service
  datasource:
    url: jdbc:postgresql://localhost:5432/iptv_db
    username: postgres
    password: oss-pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: iptv-group
