server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: internet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/internet_db
    username: postgres
    password: oss-pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # 아래 설정 추가
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: internet-group
